### ISSUE TITLE
package.json入口指向错误

### ISSUE THREAD

**Issue by 200684632** [D-xuanmo/dynamic-form#11]
npm包版本0.0.1-alpha.38
dist目录下的文件名为index.**，但是在package.json中的入口文件指向为d-form，请核查

**Comment by 200684632** [comment]
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/24392167/232952782-bc431e4d-e631-485f-b4ac-ed8b71c0d221.png">

**Comment by D-xuanmo** [comment]
@200684632 在调整打包后的文件名时，这个地方代码遗漏了，感谢提醒

**Comment by 200684632** [comment]
@D-xuanmo 
<img width="834" alt="image" src="https://user-images.githubusercontent.com/24392167/232955958-00cb1d4a-0f1e-4a08-8437-f741d3284a15.png">
这一段代码，当数据值为null的时候会报错

**Comment by D-xuanmo** [comment]
> @D-xuanmo 
> 
> <img width="834" alt="image" src="https://user-images.githubusercontent.com/24392167/232955958-00cb1d4a-0f1e-4a08-8437-f741d3284a15.png">
> 
> 这一段代码，当数据值为null的时候会报错

报什么错误，具体调用方法看一下呢

**Comment by 200684632** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/24392167/232957267-35d6130e-0a79-478b-8883-3cb03c595e2c.png">

**Comment by D-xuanmo** [comment]
> <img width="897" alt="image" src="https://user-images.githubusercontent.com/24392167/232957267-35d6130e-0a79-478b-8883-3cb03c595e2c.png">
> 
> 

你这个是模型中有些属性不存在，然后更新数据又给了这个属性是吧？

**Comment by 200684632** [comment]
@D-xuanmo 对的，因为数据比较多 没有一对一处理。

**Comment by 200684632** [comment]
@D-xuanmo 感觉当前情况下，还有要完善的，比如picker在没有默认值的情况下，选择第一项value为0会无法选中。

**Comment by D-xuanmo** [comment]
> <img alt="image" width="1516" src="https://user-images.githubusercontent.com/24392167/232952782-bc431e4d-e631-485f-b4ac-ed8b71c0d221.png">

这个问题可以在 [https://github.com/D-xuanmo/dynamic-form/issues/12](https://github.com/D-xuanmo/dynamic-form/issues/12) 这里跟进，晚点修复下

**Comment by D-xuanmo** [comment]
> @D-xuanmo 感觉当前情况下，还有要完善的，比如picker在没有默认值的情况下，选择第一项value为0会无法选中。

是的，还有很多需要完善，欢迎提意见，一起交流
