### ISSUE TITLE
[Reta]增加脚手架项目，方便快捷创建dl-ui项目

### ISSUE THREAD

**Issue by ousinka** [D-xuanmo/dynamic-form#20]
增加使用vue-cli命令创建基于dl-ui的脚手架项目，方便快捷创建项目

**Comment by D-xuanmo** [comment]
@ousinka 脚手架功能已支持 [https://www.xuanmo.xin/-/dl-ui/docs/dl-cli](https://www.xuanmo.xin/-/dl-ui/docs/dl-cli)
